config/routes.rb
Rails.application.routes.draw do
  resources :guests, only: %i(show new create edit update destroy)

  get 'chats' => 'messenger/chats#index'
  namespace :messenger do
    resources :chats, only: %i(new destroy) do
      collection { get :type }
    end
    resources :messages, only: %i(create)
  end

  root 'messenger/chats#show'

end

app/models/guest.rb
# TODO: change storage (maybe Redis?)

class Guest < ActiveRecord::Base
  before_validation do
    self.name.strip!
  end

  scope :except_one, -> person do
    all.where.not(id: person.id)
  end

  validates :name, {
    presence: true,
    length: 2..255,
    uniqueness: true
  }
end

app/models/messenger.rb
module Messenger
  def self.table_name_prefix
    'messenger_'
  end
end

require './app/units/messenger'

app/models/messenger/chat.rb
module Messenger
  class Chat < ActiveRecord::Base
    has_many :chats_people, dependent: :destroy
    has_many :people, through: :chats_people
    has_many :messages, class_name: Messenger::Message, dependent: :destroy

    scope :actual_for, -> person do
      all
        .joins(:chats_people)
        .merge ChatsPerson.actual.where(person_id: person.id)
    end

    # scope :present_for_some, -> *people do
    #   all
    #     .joins(:chats_people)
    #     .merge ChatsPerson.where(person_id: people.map(&:id))
    # end

    def companions(user)
      people.where.not(id: user.id)
    end

    def soft_destroy
      update_column(deleted_at: Time.now)
    end
  end
end

app/models/messenger/chats_person.rb
module Messenger
  class ChatsPerson < ActiveRecord::Base
    # TODO: extract 'person_class_name' setting
    belongs_to :person, class_name: 'Guest'

    scope :actual, -> { where(deleted_at: nil) }
    scope :deleted, -> { where.not(deleted_at: nil) }
  end
end

app/models/messenger/message.rb
module Messenger
  class Message < ActiveRecord::Base
    # TODO: extract 'person_class_name' setting
    belongs_to :author, class_name: 'Guest'

    validates :body, length: 1..1000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include UsersHelper

  before_action :authenticate!

  protected

  def authenticate!
    current_user.authenticated? || redirect_to(new_guest_url)
  end
end

app/controllers/concerns/messenger/helpers.rb
module Messenger
  module Helpers
    def client
      @client ||= Client.new(session_messenger)
    end

    def set_client(new_state)
      session[:messenger] = session_messenger.merge(new_state)
      client
    end
    alias :client= :set_client

    private

    def session_messenger
      session.fetch(:messenger, {}).symbolize_keys!
    end
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :authenticate!, only: %i(new create)

  before_action :set_guest, only: %i(show edit update destroy)

  def show
  end

  def new
    @guest = Guest.new
  end

  def create
    if (@guest = Guest.new(guest_params)).save
      session[:current_guest_id] = @guest.id
      redirect_to chats_url, notice: t('.welcome') and return
    end

    render :new
  end

  def edit
  end

  def update
    @guest.update(guest_params) && flash[:notice] = t('.updated')
  end

  def destroy
    @guest.destroy
    reset_session

    redirect_to root_url, notice: t('.signed_out')
  end

  private

  def set_guest
    @guest = Guest.find(params[:id])
  end

  def guest_params
    params[:guest].permit(:name)
  end
end

app/controllers/messenger/chats_controller.rb
module Messenger
  class ChatsController < ApplicationController
    include Helpers

    def index
      @guests = Guest.except_one(current_user)
    end

    def show
      redirect_to(chats_url) and return unless client.current_chat?

      @chat = GuestChat.new(client.current_chat, current_user)
    end

    def new
      @chat = OpenChat.(current_user, Guest.find(params[:guest_id]))
      set_client last_chat_id: @chat.id

      redirect_to root_url
    end

    def destroy
      @chat = Chat.find(params[:id])
      @chat.soft_destroy

      redirect_to messenger_chats_url, notice: 'Chat was successfully destroyed.'
    end

    def type
      PrivatePub.publish_to(
        "/chats/#{client.current_chat.id}",
        "App.runTypingStatus('#{current_user.id}', '#{current_user.name}')"
      )
      render nothing: true
    end
  end
end

app/controllers/messenger/messages_controller.rb
module Messenger
  class MessagesController < ApplicationController
    include Helpers

    layout :false

    def create
      @result = WriteMessage.(
        client.current_chat,
        current_user,
        Message.new(message_params)
      )
      @result.success? || render(:new)
    end

    private

    def message_params
      params.require(:messenger_message).permit(:body)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    # TODO: when using Devise replace with:
    #   @current_user ||= UserRole.new(super) || CurrentGuestFactory.(session)
    @current_user ||= CurrentGuestFactory.(session)
  end

  def signed_in?
    current_user.authenticated?
  end

  module CurrentGuestFactory extend self
    def call(state)
      GuestRole.new(find_guest(state[:current_guest_id]) || Guest.new)
    end

    private def find_guest(guest_id)
      guest_id && Guest.find_by(id: guest_id)
    end
  end
end

app/views/guests/new.slim
h1 = t('.title')

= simple_form_for @guest do |f|
  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit, t('.submit')

app/views/layouts/application.slim
doctype html
html
  head
    meta charset=Rails.application.config.encoding
    meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'
    meta name='viewport' content='width=device-width, initial-scale=1'
    title = t('app.name')

    / meta name="keywords" content=t('meta.keywords')
    / meta name="description" content=t('meta.description')
    / meta name="author" content=t('meta.author')

    /! favicons (stay in public/)
    /= favicon_link_tag '/favicon.png', rel: 'icon', type: 'image/x-icon'

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

    = javascript_include_tag 'private_pub'

    /[if lt IE 9]
      script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
      script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"

    = csrf_meta_tags
    = yield :head

  body data-current-user=current_user.to_json
    /- if current_user.authenticated?
    = render partial: 'shared/header'

    .container
      = render partial: 'shared/messages'
      = yield

    = render partial: 'shared/footer'

app/views/messenger/chats/index.html.slim
h1 = t('.title')

table
  thead
    tr
      th
      th

  tbody
    - @guests.each do |guest|
      tr
        td = link_to guest.name, new_messenger_chat_url(guest_id: guest.id)
        /td = link_to 'Destroy', chat, data: { confirm: 'Are you sure?' }, method: 'delete'

br

app/views/messenger/chats/show.html.slim
p
  = t('.companions', names: @chat.companion_list)

br

#message_list
  = render @chat.messages

br

#typing_status data-action-url=type_messenger_chats_url
  .inner
    strong
    '
    span = t('.typing')

br

#new_message_container
  = render 'messenger/messages/form', message: @chat.new_message

= subscribe_to "/chats/#{@chat.id}"

app/views/messenger/messages/_form.html.slim
= simple_form_for(message, remote: true) do |f|
  / = f.error_notification

  .form-inputs
    = f.input :body, hint: t('.message_key_hint')

  .form-actions
    = f.button :submit, t('.submit')

br

app/views/messenger/messages/_message.slim
.message
  strong = message.author_name_with_time

  br

  p = message.body

app/views/messenger/messages/create.js.erb
<% publish_to "/chats/#{@result.value.chat_id}" do %>
  $('#message_list').append('<%= escape_javascript render @result.value %>')
<% end %>

$form = $("#new_message_container form")
$form[0].reset()

$form.find(".has-error span.help-block").remove()
$form.find(".has-error").removeClass('has-error')

app/views/messenger/messages/new.js.erb
$('#new_message_container').html("<%= escape_javascript render 'messenger/messages/form', message: @result.value %>")

app/views/shared/_footer.slim
#footer
  .container
    p.text-muted = t '.copy'

app/views/shared/_header.slim
.navbar-fixed-top
  nav.navbar.navbar-default.navbar-inverse.navbar-static-top role="navigation"
    .container
      .navbar-header
        = link_to t('app.name'), root_url, class: 'navbar-brand'

      - if signed_in?
        ul.nav.navbar-nav
          li
            = link_to t('index.title', scope: 'messenger.chats'), chats_path

        ul.nav.navbar-nav.navbar-right
          li
            p.navbar-text
              = t('.user', name: current_user.name)
              '
              = current_user.status
          li
            = link_to current_user, method: 'delete' do
              = t('.sign_out')
              '
              span.glyphicon.glyphicon-log-out

app/views/shared/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"